# AndroidX
android.useAndroidX=true
android.enableJetifier=false

# JDK 17
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17.0.11

# Mémoire Gradle
org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:TieredStopAtLevel=1 -XX:CICompilerCount=2 -XX:-UseSharedSpaces -XX:+HeapDumpOnOutOfMemoryError

# Workers
org.gradle.workers.max=1
org.gradle.parallel=false

# Cache
org.gradle.caching=true
org.gradle.vfs.watch=false

# Kotlin
kotlin.daemon.jvmargs=-Xmx512m
