# --- AndroidX ---
android.useAndroidX=true
android.enableJetifier=true

# --- JDK (OK pour Windows) ---
org.gradle.java.home=C:/Program Files/Java/jdk-17.0.11

# --- Mémoire & GC (profil RAM ≤ 8 Go) ---
# Moins de heap + metaspace suffisant
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# --- Parallélisme & cache ---
# Moins de workers = moins de charge RAM/CPU
org.gradle.workers.max=4
org.gradle.parallel=true
org.gradle.caching=true

# --- Kotlin daemon (limite sa RAM aussi) ---
kotlin.daemon.jvmargs=-Xmx1024m

