# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Forcer JDK 17
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17.0.11

# Désactiver CDS (vu ton contexte)
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:-UseSharedSpaces

# Moins de workers = moins de threads = moins de mémoire native
org.gradle.workers.max=2
org.gradle.parallel=false

# Cache Gradle (optionnel)
org.gradle.caching=true

# Kotlin daemon plus léger
kotlin.daemon.jvmargs=-Xmx512m
